kpoint-labels   = ["L", "Γ", "X", "U|K", "Γ"]
procar          = "PROCAR"
outcar          = "OUTCAR"
txtout-prefix   = "pband_raw"
htmlout         = "pband.html"
segment-ranges  = [[1, 10], [11, 20], [21, 30], [31, 40]]

[pband.Si-p-orbit]
orbits  = "px py pz"
color   = "red"
