[package]
name = "rsgrad"
version = "0.1.0"
authors = ["Ionizing <PeterSmith_9@outlook.com>"]
edition = "2018"

[[bin]]
name = "rsgrad"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1"
regex = "1"
async-std = { version = "1.2.0", features = ["attributes"] }
vasp-poscar = "0.3"
clap  = "2"
termcolor = "1"
