[package]
name = "rsgrad"
version = "0.2.5"
authors = ["Ionizing <PeterSmith_9@outlook.com>"]
edition = "2018"

[[bin]]
name = "rsgrad"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1"
regex = "1"
itertools = "0.10"
#vasp-poscar = "0.3"
structopt = "0.3"
colored = "2"
log = "0.4"
env_logger = "0.8"
ndarray = "0.15"
anyhow = "1.0"

[dev-dependencies]
tempdir = "0.3"


[profile.release]
incremental = true
lto = true
opt-level = 3
