# rsgrad Band plot configuration in toml format.
# multiple tokens inside string are seperated by whitespace, if you 

# kpoint-labels   = ["G", "K", "M", "G"]   # should be consistant with the boundaries in KPOINTS
procar          = "PROCAR"
outcar          = "OUTCAR"
txtout-prefix   = "band_raw"
htmlout         = "band.html"
# segment-ranges  = [[1, 40], [41, 80], [81, 120]]  # if commented, rsgrad will find the boundaries by judging if k[i] == k[i+1]
# ncl-spinor      = "Z"     # for vasp_ncl calculation
# colormap        = "jet"     # the colormap specified to plot ncl-band
# efermi          = 0.0       # if commented, rsgrad will read the efermi from OUTCAR, but if may be slightly different from scf's

# [pband.plot1]
# spins   = "up down"     # "u d" are also ok, for ncl system, "tot x y z" are available
# atoms   = "1 3..7 -1"   # which atoms to project on, if commented, all atoms are selected
# orbits  = "s px dxy"    # which orbits to project on, if commented, all orbits are selected
# color   = "red"         # the color of marker
