[book]
authors = ["Ionizing"]
language = "en"
multilingual = false
src = "src"
title = "RSGRAD'S BOOK"

[build]
build-dir = "book"                # the directory where the output is placed
create-missing = true             # whether or not to create missing pages
use-default-preprocessors = true  # use the default preprocessors

[output.html]
default-theme = "rust"
mathjax-support = true

[output.html.fold]
enable = true
level = 1

[output.markdown]

#[output.pdf]
