name: Rust

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-18.04
    container: centos:7
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      run: |
        yum install -y gcc g++ which
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y --target x86_64-unknown-linux-musl x86_64-unknown-linux-gnu
        echo $HOME/.cargo/bin >> $GITHUB_PATH
        source $HOME/.cargo/env
        which rustup
        which cargo
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release
    - name: Run integrated tests
      run: for i in tests/OUTCAR_* ; do cargo run --release -- rlx $i; done
